--[[
	Nissan Silvia S15 Spec R - Roblox setup script
	Generated by s15_spec_r.py. Run ONCE in Roblox Studio:

	  1. Import S15_SpecR_Roblox.fbx with the 3D Importer
	     (File Transform: Scale Unit = Stud, World Forward = Front, World Up = Top).
	  2. Select the imported model in the Explorer.
	  3. Paste this whole file into View > Command Bar and press Enter.

	What it does:
	  * paints every MeshPart (material / colour / transparency / reflectance)
	  * builds the A-Chassis layout: Body, Wheels/FL,FR,RL,RR (+Parts, +Fixed),
	    Misc/Door_L, Door_R, Hood, Trunk, SteeringWheel and a DriveSeat (RHD)
	  * adds hinge data + ProximityPrompts so doors, hood and boot open
	  * adds S15_Panels + S15_Lights server scripts and an A-Chassis plugin
	    ("S15 Lights Plugin") - move that plugin into "A-Chassis Tune/Plugins".
]]

local Selection = game:GetService("Selection")
local src = Selection:Get()[1]
assert(src and (src:IsA("Model") or src:IsA("Folder")), "Select the imported S15 model in the Explorer first")

local LOOKS = {
	Aluminum = { "Metal", { 210, 212, 216 }, 0, 0.25 },
	AmberReflector = { "SmoothPlastic", { 255, 150, 20 }, 0, 0.1 },
	Badge = { "SmoothPlastic", { 215, 215, 220 }, 0, 0.5 },
	Battery = { "SmoothPlastic", { 25, 25, 30 }, 0, 0 },
	BlackGloss = { "SmoothPlastic", { 25, 25, 29 }, 0, 0.08 },
	BlackMatte = { "Plastic", { 36, 36, 39 }, 0, 0 },
	Brake = { "Metal", { 130, 130, 132 }, 0, 0.05 },
	BulbRed = { "SmoothPlastic", { 200, 10, 10 }, 0, 0.1 },
	Caliper = { "SmoothPlastic", { 70, 70, 76 }, 0, 0.05 },
	Carpet = { "Fabric", { 20, 20, 22 }, 0, 0 },
	Chrome = { "SmoothPlastic", { 200, 200, 205 }, 0, 0.45 },
	CoilPack = { "SmoothPlastic", { 25, 25, 28 }, 0, 0 },
	Coupler = { "SmoothPlastic", { 30, 70, 170 }, 0, 0 },
	Emitter = { "SmoothPlastic", { 240, 240, 230 }, 0, 0.1 },
	EngineBlock = { "Metal", { 150, 152, 156 }, 0, 0.05 },
	Exhaust = { "Metal", { 170, 170, 175 }, 0, 0.2 },
	Gauge = { "SmoothPlastic", { 8, 8, 10 }, 0, 0.1 },
	GaugeMark = { "SmoothPlastic", { 235, 235, 235 }, 0, 0 },
	Glass = { "Glass", { 70, 82, 84 }, 0.55, 0.15 },
	Headliner = { "Fabric", { 150, 150, 146 }, 0, 0 },
	Hose = { "Plastic", { 20, 20, 22 }, 0, 0 },
	Housing = { "SmoothPlastic", { 18, 18, 20 }, 0, 0 },
	Interior = { "Fabric", { 34, 34, 37 }, 0, 0 },
	InteriorTrim = { "SmoothPlastic", { 45, 45, 48 }, 0, 0 },
	Leather = { "SmoothPlastic", { 30, 30, 32 }, 0, 0 },
	LensAmber = { "Glass", { 255, 140, 0 }, 0.2, 0.05 },
	LensClear = { "Glass", { 235, 240, 245 }, 0.6, 0.1 },
	LensRed = { "Glass", { 110, 8, 12 }, 0.35, 0.05 },
	LensSmoke = { "Glass", { 40, 40, 44 }, 0.4, 0.05 },
	Mirror = { "SmoothPlastic", { 210, 215, 220 }, 0, 0.85 },
	Needle = { "Neon", { 255, 60, 10 }, 0, 0 },
	Paint = { "SmoothPlastic", { 229, 200, 13 }, 0, 0.08 },
	PlateText = { "SmoothPlastic", { 10, 90, 40 }, 0, 0 },
	PlateWhite = { "SmoothPlastic", { 238, 240, 236 }, 0, 0 },
	Radiator = { "Metal", { 45, 45, 48 }, 0, 0 },
	Reflector = { "SmoothPlastic", { 200, 200, 205 }, 0, 0.5 },
	Rim = { "Metal", { 190, 192, 196 }, 0, 0.15 },
	Rubber = { "SmoothPlastic", { 28, 28, 28 }, 0, 0 },
	Seat = { "Fabric", { 25, 25, 27 }, 0, 0 },
	SeatAccent = { "Fabric", { 70, 70, 74 }, 0, 0 },
	TailAmber = { "Glass", { 150, 70, 10 }, 0.35, 0.05 },
	Terminal = { "SmoothPlastic", { 200, 20, 20 }, 0, 0 },
	Translucent = { "Glass", { 235, 235, 225 }, 0.3, 0 },
	Turbine = { "Metal", { 90, 80, 72 }, 0, 0 },
	Underbody = { "Plastic", { 22, 22, 24 }, 0, 0 },
	ValveCover = { "SmoothPlastic", { 170, 20, 20 }, 0, 0.05 },
}
local PARTS = {
	Body_Aluminum = { "Body", "Aluminum" },
	Body_AmberReflector = { "Body", "AmberReflector" },
	Body_Battery = { "Body", "Battery" },
	Body_BlackGloss = { "Body", "BlackGloss" },
	Body_BlackMatte = { "Body", "BlackMatte" },
	Body_BulbRed = { "Body", "BulbRed" },
	Body_Carpet = { "Body", "Carpet" },
	Body_Chrome = { "Body", "Chrome" },
	Body_CoilPack = { "Body", "CoilPack" },
	Body_Coupler = { "Body", "Coupler" },
	Body_EngineBlock = { "Body", "EngineBlock" },
	Body_Exhaust = { "Body", "Exhaust" },
	Body_Gauge = { "Body", "Gauge" },
	Body_GaugeMark = { "Body", "GaugeMark" },
	Body_Glass = { "Body", "Glass" },
	Body_Headliner = { "Body", "Headliner" },
	Body_Hose = { "Body", "Hose" },
	Body_Housing = { "Body", "Housing" },
	Body_Interior = { "Body", "Interior" },
	Body_InteriorTrim = { "Body", "InteriorTrim" },
	Body_Leather = { "Body", "Leather" },
	Body_LensClear = { "Body", "LensClear" },
	Body_Mirror = { "Body", "Mirror" },
	Body_Paint_1 = { "Body", "Paint" },
	Body_Paint_2 = { "Body", "Paint" },
	Body_Paint_3 = { "Body", "Paint" },
	Body_Paint_4 = { "Body", "Paint" },
	Body_PlateText = { "Body", "PlateText" },
	Body_PlateWhite = { "Body", "PlateWhite" },
	Body_Radiator = { "Body", "Radiator" },
	Body_Reflector = { "Body", "Reflector" },
	Body_Rubber = { "Body", "Rubber" },
	Body_Seat = { "Body", "Seat" },
	Body_SeatAccent = { "Body", "SeatAccent" },
	Body_Terminal = { "Body", "Terminal" },
	Body_Translucent = { "Body", "Translucent" },
	Body_Turbine = { "Body", "Turbine" },
	Body_Underbody = { "Body", "Underbody" },
	Body_ValveCover = { "Body", "ValveCover" },
	Caliper_FL_Caliper = { "Caliper_FL", "Caliper" },
	Caliper_FR_Caliper = { "Caliper_FR", "Caliper" },
	Caliper_RL_Caliper = { "Caliper_RL", "Caliper" },
	Caliper_RR_Caliper = { "Caliper_RR", "Caliper" },
	Door_L_BlackGloss = { "Door_L", "BlackGloss" },
	Door_L_BlackMatte = { "Door_L", "BlackMatte" },
	Door_L_Chrome = { "Door_L", "Chrome" },
	Door_L_Glass = { "Door_L", "Glass" },
	Door_L_Interior = { "Door_L", "Interior" },
	Door_L_InteriorTrim = { "Door_L", "InteriorTrim" },
	Door_L_Mirror = { "Door_L", "Mirror" },
	Door_L_Paint = { "Door_L", "Paint" },
	Door_R_BlackGloss = { "Door_R", "BlackGloss" },
	Door_R_BlackMatte = { "Door_R", "BlackMatte" },
	Door_R_Chrome = { "Door_R", "Chrome" },
	Door_R_Glass = { "Door_R", "Glass" },
	Door_R_Interior = { "Door_R", "Interior" },
	Door_R_InteriorTrim = { "Door_R", "InteriorTrim" },
	Door_R_Mirror = { "Door_R", "Mirror" },
	Door_R_Paint = { "Door_R", "Paint" },
	Hood_Badge = { "Hood", "Badge" },
	Hood_BlackMatte = { "Hood", "BlackMatte" },
	Hood_Interior = { "Hood", "Interior" },
	Hood_Paint = { "Hood", "Paint" },
	Hood_Reflector = { "Hood", "Reflector" },
	Light_Brake_C = { "Trunk", "LensRed" },
	Light_Brake_L = { "Body", "LensRed" },
	Light_Brake_R = { "Body", "LensRed" },
	Light_Dash = { "Body", "Needle" },
	Light_Head_L = { "Body", "Emitter" },
	Light_Head_R = { "Body", "Emitter" },
	Light_Indicator_FL = { "Body", "LensAmber" },
	Light_Indicator_FR = { "Body", "LensAmber" },
	Light_Indicator_RL = { "Body", "TailAmber" },
	Light_Indicator_RR = { "Body", "TailAmber" },
	Light_Indicator_SL = { "Body", "LensAmber" },
	Light_Indicator_SR = { "Body", "LensAmber" },
	Light_Plate = { "Body", "LensClear" },
	Light_Reverse_L = { "Body", "LensSmoke" },
	Light_Reverse_R = { "Body", "LensSmoke" },
	SteeringWheel_Leather = { "SteeringWheel", "Leather" },
	Trunk_Badge = { "Trunk", "Badge" },
	Trunk_Housing = { "Trunk", "Housing" },
	Trunk_Interior = { "Trunk", "Interior" },
	Trunk_Paint = { "Trunk", "Paint" },
	Trunk_Terminal = { "Trunk", "Terminal" },
	Wheel_FL_Badge = { "Wheel_FL", "Badge" },
	Wheel_FL_Brake = { "Wheel_FL", "Brake" },
	Wheel_FL_Chrome = { "Wheel_FL", "Chrome" },
	Wheel_FL_Rim = { "Wheel_FL", "Rim" },
	Wheel_FL_Rubber = { "Wheel_FL", "Rubber" },
	Wheel_FL_Underbody = { "Wheel_FL", "Underbody" },
	Wheel_FR_Badge = { "Wheel_FR", "Badge" },
	Wheel_FR_Brake = { "Wheel_FR", "Brake" },
	Wheel_FR_Chrome = { "Wheel_FR", "Chrome" },
	Wheel_FR_Rim = { "Wheel_FR", "Rim" },
	Wheel_FR_Rubber = { "Wheel_FR", "Rubber" },
	Wheel_FR_Underbody = { "Wheel_FR", "Underbody" },
	Wheel_RL_Badge = { "Wheel_RL", "Badge" },
	Wheel_RL_Brake = { "Wheel_RL", "Brake" },
	Wheel_RL_Chrome = { "Wheel_RL", "Chrome" },
	Wheel_RL_Rim = { "Wheel_RL", "Rim" },
	Wheel_RL_Rubber = { "Wheel_RL", "Rubber" },
	Wheel_RL_Underbody = { "Wheel_RL", "Underbody" },
	Wheel_RR_Badge = { "Wheel_RR", "Badge" },
	Wheel_RR_Brake = { "Wheel_RR", "Brake" },
	Wheel_RR_Chrome = { "Wheel_RR", "Chrome" },
	Wheel_RR_Rim = { "Wheel_RR", "Rim" },
	Wheel_RR_Rubber = { "Wheel_RR", "Rubber" },
	Wheel_RR_Underbody = { "Wheel_RR", "Underbody" },
}
local HINGES = {
	Door_L = {
		angle = -62,
		axis = { 0, 1, 0 },
		label = "Left door",
		pivot = { -2.857, 0.8477, 2.5 },
	},
	Door_R = {
		angle = 62,
		axis = { 0, 1, 0 },
		label = "Right door",
		pivot = { 2.857, 0.8477, 2.5 },
	},
	Hood = {
		angle = 52,
		axis = { 1, 0, 0 },
		label = "Bonnet",
		pivot = { -0, 2.026, 2.911 },
	},
	Trunk = {
		angle = -58,
		axis = { 1, 0, 0 },
		label = "Boot",
		pivot = { -0, 2.319, -5.471 },
	},
}
local SEATS = {
	driver = { 1.321, 0.6691, -1.143 },
	passenger = { -1.321, 0.6691, -1.143 },
}
local STEER = {
	axis = { -0, 0.423, -0.9061 },
	hub = { 1.321, 1.633, 0.9286 },
}
local WHEEL_SIZE = { 0.7679, 2.233 }
local WHEELBASE = 9.0179
local ANCHOR = "Body_Paint_2"

-- collect the imported MeshParts by name
local meshes = {}
for _, d in ipairs(src:GetDescendants()) do
	if d:IsA("MeshPart") then
		meshes[d.Name] = d
	end
end
for name in pairs(PARTS) do
	if not meshes[name] then
		warn("[S15] missing part " .. name)
	end
end

-- looks
for name, part in pairs(meshes) do
	local info = PARTS[name]
	if info then
		local look = LOOKS[info[2]]
		part.Material = Enum.Material[look[1]]
		part.Color = Color3.fromRGB(look[2][1], look[2][2], look[2][3])
		part.Transparency = look[3]
		part.Reflectance = look[4]
		part.CastShadow = look[3] < 0.3
	end
	part.Anchored = true
	part.CanCollide = false
	part.CanTouch = false
	part.CanQuery = true
end

-- the car's own frame, measured from the four tyres
local function pos(n)
	local p = meshes[n]
	assert(p, "missing " .. n)
	return p.Position
end
local FL, FR = pos("Wheel_FL_Rubber"), pos("Wheel_FR_Rubber")
local RL, RR = pos("Wheel_RL_Rubber"), pos("Wheel_RR_Rubber")
local origin = (FL + FR + RL + RR) / 4
local fwd = ((FL + FR) / 2 - (RL + RR) / 2).Unit
local right = (FR - FL).Unit
local up = right:Cross(fwd).Unit
if up.Y < 0.5 then
	warn("[S15] the import looks mirrored or upside down - check the importer's World Up / World Forward settings")
end
-- tolerate an import at another scale: measure the wheelbase
local scale = ((FL + FR) / 2 - (RL + RR) / 2).Magnitude / WHEELBASE
if math.abs(scale - 1) > 0.02 then
	warn(string.format("[S15] model is %.2fx the expected stud scale - offsets scaled to match", scale))
end
local function W(p) -- car-local studs {right, up, forward} -> world
	return origin + (right * p[1] + up * p[2] + fwd * p[3]) * scale
end
local function V(d)
	return right * d[1] + up * d[2] + fwd * d[3]
end
-- hierarchy -----------------------------------------------------------------
local car = Instance.new("Model")
car.Name = "Nissan Silvia S15 Spec R"
local body = Instance.new("Model")
body.Name = "Body"
body.Parent = car
local wheels = Instance.new("Model")
wheels.Name = "Wheels"
wheels.Parent = car
local misc = Instance.new("Model")
misc.Name = "Misc"
misc.Parent = car

local miscModels = {}
for _, n in ipairs({ "Door_L", "Door_R", "Hood", "Trunk", "SteeringWheel" }) do
	local m = Instance.new("Model")
	m.Name = n
	m.Parent = misc
	miscModels[n] = m
end

for _, k in ipairs({ "FL", "FR", "RL", "RR" }) do
	local tyre = meshes["Wheel_" .. k .. "_Rubber"]
	local w = Instance.new("Part")
	w.Name = k
	w.Shape = Enum.PartType.Cylinder
	w.Size = Vector3.new(WHEEL_SIZE[1], WHEEL_SIZE[2], WHEEL_SIZE[2]) * scale
	w.CFrame = CFrame.fromMatrix(tyre.Position, right, up)
	w.Transparency = 1
	w.Anchored = true
	w.CanCollide = false
	w.Parent = wheels
	local p = Instance.new("Model")
	p.Name = "Parts"
	p.Parent = w
	local f = Instance.new("Model")
	f.Name = "Fixed"
	f.Parent = w
	miscModels["Wheel_" .. k] = p
	miscModels["Caliper_" .. k] = f
end

for name, part in pairs(meshes) do
	local info = PARTS[name]
	local asm = info and info[1] or "Body"
	part.Parent = miscModels[asm] or body
end

local anchor = meshes[ANCHOR]
body.PrimaryPart = anchor
for n, m in pairs(miscModels) do
	if m:IsA("Model") and #m:GetChildren() > 0 and not m.PrimaryPart then
		local best
		for _, c in ipairs(m:GetChildren()) do
			if c:IsA("BasePart") and (not best or c.Size.Magnitude > best.Size.Magnitude) then
				best = c
			end
		end
		m.PrimaryPart = best
	end
end

-- seats (right-hand drive)
local function makeSeat(class, name, p)
	local s = Instance.new(class)
	s.Name = name
	s.Size = Vector3.new(1.6, 0.6, 1.6) * scale
	s.CFrame = CFrame.fromMatrix(W(p), right, up)
	s.Transparency = 1
	s.Anchored = true
	s.CanCollide = false
	s.Parent = (class == "VehicleSeat") and car or body
	return s
end
local seat = makeSeat("VehicleSeat", "DriveSeat", SEATS.driver)
makeSeat("Seat", "PassengerSeat", SEATS.passenger)

-- opening panels: hinge frame stored relative to the body anchor -------------
for n, h in pairs(HINGES) do
	local m = miscModels[n]
	local axis = V(h.axis).Unit
	local perp = math.abs(axis:Dot(up)) > 0.9 and fwd or up
	perp = (perp - axis * axis:Dot(perp)).Unit
	local hcf = CFrame.fromMatrix(W(h.pivot), axis, perp)
	m:SetAttribute("HingeOffset", anchor.CFrame:ToObjectSpace(hcf))
	m:SetAttribute("OpenAngle", h.angle)
	local prompt = Instance.new("ProximityPrompt")
	prompt.Name = "OpenPrompt"
	prompt.ActionText = "Open"
	prompt.ObjectText = h.label
	prompt.HoldDuration = 0
	prompt.MaxActivationDistance = 9
	prompt.RequiresLineOfSight = false
	prompt.KeyboardKeyCode = Enum.KeyCode.F
	prompt.Parent = m.PrimaryPart
end

-- steering wheel spin axis
do
	local sw = miscModels.SteeringWheel
	local axis = V(STEER.axis).Unit
	local x = up:Cross(axis).Unit
	local y = axis:Cross(x).Unit
	-- hub frame: Z = steering column axis
	sw:SetAttribute("HubOffset", anchor.CFrame:ToObjectSpace(CFrame.fromMatrix(W(STEER.hub), x, y)))
end

-- runtime scripts --------------------------------------------------------------
local lightEvent = Instance.new("RemoteEvent")
lightEvent.Name = "S15_LightEvent"
lightEvent.Parent = car

local panels = Instance.new("Script")
panels.Name = "S15_Panels"
panels.Source = [==[-- Doors / hood / boot: ProximityPrompt toggles. Works on an anchored
-- display car (tweens) and on a driving A-Chassis car (servo hinges).
local TweenService = game:GetService("TweenService")
local car = script.Parent
local body = car:WaitForChild("Body")
local anchor = body.PrimaryPart or body:FindFirstChildWhichIsA("BasePart")
local misc = car:WaitForChild("Misc")

local function setup(panel)
	local main = panel.PrimaryPart
	local off = panel:GetAttribute("HingeOffset")
	local angle = panel:GetAttribute("OpenAngle")
	if not (main and off and angle) then
		return
	end
	-- glue the panel's pieces to its main part
	for _, p in ipairs(panel:GetDescendants()) do
		if p:IsA("BasePart") then
			p.Massless = true
			if p ~= main then
				local w = Instance.new("WeldConstraint")
				w.Part0, w.Part1 = main, p
				w.Parent = main
			end
		end
	end
	-- physical hinge (used once the chassis unanchors the car)
	local a0 = Instance.new("Attachment")
	a0.Name = panel.Name .. "_Hinge0"
	a0.CFrame = off
	a0.Parent = anchor
	local a1 = Instance.new("Attachment")
	a1.Name = "Hinge1"
	a1.CFrame = main.CFrame:ToObjectSpace(anchor.CFrame * off)
	a1.Parent = main
	local h = Instance.new("HingeConstraint")
	h.Attachment0, h.Attachment1 = a0, a1
	h.ActuatorType = Enum.ActuatorType.Servo
	h.ServoMaxTorque = 1e7
	h.AngularSpeed = 2.5
	h.TargetAngle = 0
	h.LimitsEnabled = true
	h.LowerAngle = math.min(0, angle) - 1
	h.UpperAngle = math.max(0, angle) + 1
	h.Parent = main

	local open = false
	-- closed pose relative to the hinge (for the anchored / display mode)
	local closedRel = (anchor.CFrame * off):ToObjectSpace(panel:GetPivot())
	local driver = Instance.new("NumberValue")
	driver.Changed:Connect(function(t)
		if main.Anchored then
			local hcf = anchor.CFrame * off
			panel:PivotTo(hcf * CFrame.Angles(math.rad(angle * t), 0, 0) * closedRel)
		end
	end)
	-- when the chassis unanchors the car, let the panel ride on its hinge
	anchor:GetPropertyChangedSignal("Anchored"):Connect(function()
		if not anchor.Anchored then
			for _, p in ipairs(panel:GetDescendants()) do
				if p:IsA("BasePart") then
					p.Anchored = false
				end
			end
			h.TargetAngle = open and angle or 0
		end
	end)
	local prompt = main:FindFirstChild("OpenPrompt")
	prompt.Triggered:Connect(function()
		open = not open
		prompt.ActionText = open and "Close" or "Open"
		if main.Anchored then
			TweenService:Create(driver, TweenInfo.new(0.8, Enum.EasingStyle.Quad), { Value = open and 1 or 0 }):Play()
		else
			h.TargetAngle = open and angle or 0
		end
	end)
end

for _, n in ipairs({ "Door_L", "Door_R", "Hood", "Trunk" }) do
	local m = misc:FindFirstChild(n)
	if m then
		setup(m)
	end
end

-- steering wheel follows the steering input (set by the light plugin)
local sw = misc:FindFirstChild("SteeringWheel")
if sw and sw.PrimaryPart then
	local hub = sw:GetAttribute("HubOffset")
	for _, p in ipairs(sw:GetDescendants()) do
		if p:IsA("BasePart") and p ~= sw.PrimaryPart then
			local w = Instance.new("WeldConstraint")
			w.Part0, w.Part1 = sw.PrimaryPart, p
			w.Parent = p
		end
	end
	local m6 = Instance.new("Motor6D")
	m6.Name = "SteerMotor"
	m6.Part0 = anchor
	m6.Part1 = sw.PrimaryPart
	m6.C0 = hub
	m6.C1 = sw.PrimaryPart.CFrame:ToObjectSpace(anchor.CFrame * hub)
	m6.Parent = sw.PrimaryPart
	anchor:GetPropertyChangedSignal("Anchored"):Connect(function()
		if not anchor.Anchored then
			for _, p in ipairs(sw:GetDescendants()) do
				if p:IsA("BasePart") then
					p.Anchored = false
					p.Massless = true
				end
			end
		end
	end)
	car:GetAttributeChangedSignal("Steer"):Connect(function()
		local s = car:GetAttribute("Steer") or 0
		m6.Transform = CFrame.Angles(0, 0, -math.rad(270) * s)
	end)
end
]==]
panels.Parent = car

local lights = Instance.new("Script")
lights.Name = "S15_Lights"
lights.Source = [==[-- Working lights. Driven by the "S15 Lights Plugin" (A-Chassis) through
-- S15_LightEvent, or by car attributes: Headlights, Brake, Reverse,
-- IndicatorLeft, IndicatorRight, Hazards (booleans).
local car = script.Parent
local event = car:WaitForChild("S15_LightEvent")

local lights = {}
for _, d in ipairs(car:GetDescendants()) do
	if d:IsA("BasePart") and d.Name:sub(1, 6) == "Light_" then
		lights[d.Name] = { part = d, Material = d.Material, Color = d.Color, Transparency = d.Transparency }
	end
end

local function set(name, on, color)
	local l = lights[name]
	if not l then
		return
	end
	if on then
		l.part.Material = Enum.Material.Neon
		l.part.Color = color
		l.part.Transparency = 0
	else
		l.part.Material, l.part.Color, l.part.Transparency = l.Material, l.Color, l.Transparency
	end
end

-- headlight beams
local beams = {}
for _, n in ipairs({ "Light_Head_L", "Light_Head_R" }) do
	local l = lights[n]
	if l then
		local body = car:FindFirstChild("Wheels")
		local fl, rl = body and body:FindFirstChild("FL"), body and body:FindFirstChild("RL")
		local fwd = (fl and rl) and (fl.Position - rl.Position).Unit or l.part.CFrame.LookVector
		local a = Instance.new("Attachment")
		a.CFrame = CFrame.lookAt(Vector3.zero, l.part.CFrame:VectorToObjectSpace(fwd) + Vector3.new(0, -0.06, 0))
		a.Parent = l.part
		local s = Instance.new("SpotLight")
		s.Brightness = 3
		s.Range = 60
		s.Angle = 60
		s.Face = Enum.NormalId.Front
		s.Shadows = true
		s.Enabled = false
		s.Parent = a
		table.insert(beams, s)
	end
end

local WHITE = Color3.fromRGB(255, 250, 235)
local TAIL = Color3.fromRGB(120, 0, 0)
local BRAKE = Color3.fromRGB(255, 20, 20)
local AMBER = Color3.fromRGB(255, 150, 0)
local blink = false

local function refresh()
	local head = car:GetAttribute("Headlights") == true
	local brake = car:GetAttribute("Brake") == true
	local rev = car:GetAttribute("Reverse") == true
	local haz = car:GetAttribute("Hazards") == true
	local il = car:GetAttribute("IndicatorLeft") == true or haz
	local ir = car:GetAttribute("IndicatorRight") == true or haz
	for _, n in ipairs({ "Light_Head_L", "Light_Head_R", "Light_Plate", "Light_Dash" }) do
		set(n, head, n == "Light_Dash" and Color3.fromRGB(255, 70, 20) or WHITE)
	end
	for _, b in ipairs(beams) do
		b.Enabled = head
	end
	for _, n in ipairs({ "Light_Brake_L", "Light_Brake_R" }) do
		set(n, brake or head, brake and BRAKE or TAIL)
	end
	set("Light_Brake_C", brake, BRAKE)
	set("Light_Reverse_L", rev, WHITE)
	set("Light_Reverse_R", rev, WHITE)
	for _, n in ipairs({ "Light_Indicator_FL", "Light_Indicator_SL", "Light_Indicator_RL" }) do
		set(n, il and blink, AMBER)
	end
	for _, n in ipairs({ "Light_Indicator_FR", "Light_Indicator_SR", "Light_Indicator_RR" }) do
		set(n, ir and blink, AMBER)
	end
end

event.OnServerEvent:Connect(function(player, state)
	local seat = car:FindFirstChild("DriveSeat")
	if not (seat and seat.Occupant and seat.Occupant.Parent == player.Character) then
		return
	end
	for k, v in pairs(state) do
		if k == "Steer" then
			car:SetAttribute("Steer", math.clamp(tonumber(v) or 0, -1, 1))
		elseif k == "Headlights" or k == "Brake" or k == "Reverse" or k == "IndicatorLeft"
			or k == "IndicatorRight" or k == "Hazards" then
			car:SetAttribute(k, v == true)
		end
	end
end)

car.AttributeChanged:Connect(refresh)
refresh()
while true do
	task.wait(0.4)
	blink = not blink
	refresh()
end
]==]
lights.Parent = car

local pluginFolder = Instance.new("Folder")
pluginFolder.Name = "Move into A-Chassis Tune > Plugins"
pluginFolder.Parent = car
local plug = Instance.new("LocalScript")
plug.Name = "S15 Lights Plugin"
plug.Source = [==[-- A-Chassis plugin: put this LocalScript in "A-Chassis Tune > Plugins".
-- L = headlights, Z / C = left / right indicator, X = hazards.
local UIS = game:GetService("UserInputService")
local iface = script.Parent
local car = iface:WaitForChild("Car").Value
local values = iface:WaitForChild("Values")
local event = car:WaitForChild("S15_LightEvent")

local state = { Headlights = false, IndicatorLeft = false, IndicatorRight = false, Hazards = false }
local last = { Brake = false, Reverse = false, Steer = 0 }

local function send(t)
	event:FireServer(t)
end

UIS.InputBegan:Connect(function(input, gp)
	if gp then
		return
	end
	local k = input.KeyCode
	if k == Enum.KeyCode.L then
		state.Headlights = not state.Headlights
	elseif k == Enum.KeyCode.Z then
		state.IndicatorLeft = not state.IndicatorLeft
		state.IndicatorRight = false
	elseif k == Enum.KeyCode.C then
		state.IndicatorRight = not state.IndicatorRight
		state.IndicatorLeft = false
	elseif k == Enum.KeyCode.X then
		state.Hazards = not state.Hazards
	else
		return
	end
	send(state)
end)

local function num(name)
	local v = values:FindFirstChild(name)
	return v and tonumber(v.Value) or 0
end

while task.wait(0.1) do
	local gear = num("Gear")
	local brake = num("Brake") > 0.05
	local steer = values:FindFirstChild("SteerC") and num("SteerC") or num("SteerT")
	local t = { Brake = brake, Reverse = gear < 0, Steer = math.floor(steer * 50 + 0.5) / 50 }
	if t.Brake ~= last.Brake or t.Reverse ~= last.Reverse or t.Steer ~= last.Steer then
		last = t
		send(t)
	end
end
]==]
plug.Parent = pluginFolder

car.PrimaryPart = seat
car.Parent = src.Parent or workspace
src:Destroy()
Selection:Set({ car })
print("[S15] done: " .. #car:GetDescendants() .. " instances. Drop the A-Chassis Tune into the model next.")
